export const UPDATE_FOCUS='UPDATE_FOCUS';
export const UPDATE_ZOOM='UPDATE_ZOOM';
export const UPDATE_FOCUSZOOM = 'UPDATE_FOCUSZOOM';


export const UPDATE_TABOPEN ='UPDATE_TABOPEN';
export const TURNON_SHOWALL ='TURNON_SHOWALL';
export const TOGGLE_SHOWALL = 'TOGGLE_SHOWALL';

export const UPDATE_SEARCHBARRESULT = 'UPDATE_SEARCHBARRESULT';
export const UPDATE_CURRENTPIN ='UPDATE_CURRENTPIN';

export const RESTORE_MAPCONFIG = 'RESTORE_MAPCONFIG';